import type {
  Client,
  Product,
  Order,
  ScheduleEvent,
  DashboardStats,
} from "./types";

export const mockClients: Client[] = [
  {
    id: "1",
    name: "Ana Paula Ferreira",
    email: "ana.paula@email.com",
    phone: "11987654321",
    city: "São Paulo",
    address: "Rua das Flores, 123",
    status: "ativa",
    birthday: "1990-03-15",
    notes: "Prefere produtos naturais. Cliente fiel desde 2022.",
    created_at: "2022-05-10",
    total_orders: 12,
    total_spent: 1480.0,
    last_order_date: "2026-04-28",
  },
  {
    id: "2",
    name: "Camila Rodrigues",
    email: "camila.r@email.com",
    phone: "11976543210",
    city: "São Paulo",
    status: "ativa",
    birthday: "1995-07-22",
    created_at: "2023-01-15",
    total_orders: 8,
    total_spent: 920.0,
    last_order_date: "2026-05-10",
  },
  {
    id: "3",
    name: "Juliana Mendes",
    phone: "11965432109",
    city: "Guarulhos",
    status: "prospect",
    created_at: "2026-04-20",
    total_orders: 0,
    total_spent: 0,
  },
  {
    id: "4",
    name: "Fernanda Costa",
    email: "fernanda.costa@email.com",
    phone: "11954321098",
    city: "Osasco",
    status: "ativa",
    birthday: "1988-11-30",
    created_at: "2022-08-01",
    total_orders: 20,
    total_spent: 2650.0,
    last_order_date: "2026-05-14",
  },
  {
    id: "5",
    name: "Beatriz Lima",
    phone: "11943210987",
    city: "Santo André",
    status: "inativa",
    created_at: "2023-03-10",
    total_orders: 3,
    total_spent: 340.0,
    last_order_date: "2025-11-05",
  },
  {
    id: "6",
    name: "Mariana Souza",
    email: "mari.souza@email.com",
    phone: "11932109876",
    city: "São Bernardo",
    status: "ativa",
    birthday: "1992-06-08",
    created_at: "2023-06-20",
    total_orders: 6,
    total_spent: 780.0,
    last_order_date: "2026-05-01",
  },
];

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Base Líquida Cobertura Total",
    brand: "Mary Kay",
    category: "Maquiagem",
    cost_price: 45.0,
    sale_price: 85.0,
    stock: 12,
    created_at: "2025-01-10",
  },
  {
    id: "2",
    name: "Hidratante Facial FPS 30",
    brand: "Avon",
    category: "Skincare",
    cost_price: 28.0,
    sale_price: 55.0,
    stock: 8,
    created_at: "2025-01-10",
  },
  {
    id: "3",
    name: "Batom Matte Nude",
    brand: "Mary Kay",
    category: "Maquiagem",
    cost_price: 18.0,
    sale_price: 38.0,
    stock: 25,
    created_at: "2025-02-05",
  },
  {
    id: "4",
    name: "Máscara de Cílios Volume",
    brand: "Natura",
    category: "Maquiagem",
    cost_price: 22.0,
    sale_price: 48.0,
    stock: 15,
    created_at: "2025-02-10",
  },
  {
    id: "5",
    name: "Perfume Deo Colônia Floral",
    brand: "Avon",
    category: "Perfumaria",
    cost_price: 35.0,
    sale_price: 72.0,
    stock: 6,
    created_at: "2025-03-01",
  },
  {
    id: "6",
    name: "Creme Anti-idade Noturno",
    brand: "Natura",
    category: "Skincare",
    cost_price: 52.0,
    sale_price: 98.0,
    stock: 4,
    created_at: "2025-03-15",
  },
  {
    id: "7",
    name: "Paleta de Sombras Nude",
    brand: "Mary Kay",
    category: "Maquiagem",
    cost_price: 65.0,
    sale_price: 120.0,
    stock: 7,
    created_at: "2025-04-01",
  },
  {
    id: "8",
    name: "Shampoo Cachos Definidos",
    brand: "Avon",
    category: "Cabelos",
    cost_price: 20.0,
    sale_price: 42.0,
    stock: 18,
    created_at: "2025-04-10",
  },
];

export const mockOrders: Order[] = [
  {
    id: "1",
    client_id: "4",
    client_name: "Fernanda Costa",
    items: [
      {
        product_id: "1",
        product_name: "Base Líquida Cobertura Total",
        quantity: 1,
        unit_price: 85.0,
        subtotal: 85.0,
      },
      {
        product_id: "3",
        product_name: "Batom Matte Nude",
        quantity: 2,
        unit_price: 38.0,
        subtotal: 76.0,
      },
    ],
    total: 161.0,
    status: "entregue",
    payment_method: "pix",
    created_at: "2026-05-14",
  },
  {
    id: "2",
    client_id: "2",
    client_name: "Camila Rodrigues",
    items: [
      {
        product_id: "2",
        product_name: "Hidratante Facial FPS 30",
        quantity: 1,
        unit_price: 55.0,
        subtotal: 55.0,
      },
      {
        product_id: "6",
        product_name: "Creme Anti-idade Noturno",
        quantity: 1,
        unit_price: 98.0,
        subtotal: 98.0,
      },
    ],
    total: 153.0,
    status: "confirmado",
    payment_method: "dinheiro",
    created_at: "2026-05-10",
  },
  {
    id: "3",
    client_id: "6",
    client_name: "Mariana Souza",
    items: [
      {
        product_id: "5",
        product_name: "Perfume Deo Colônia Floral",
        quantity: 1,
        unit_price: 72.0,
        subtotal: 72.0,
      },
    ],
    total: 72.0,
    status: "pendente",
    payment_method: "dinheiro",
    created_at: "2026-05-12",
  },
  {
    id: "4",
    client_id: "1",
    client_name: "Ana Paula Ferreira",
    items: [
      {
        product_id: "7",
        product_name: "Paleta de Sombras Nude",
        quantity: 1,
        unit_price: 120.0,
        subtotal: 120.0,
      },
      {
        product_id: "4",
        product_name: "Máscara de Cílios Volume",
        quantity: 1,
        unit_price: 48.0,
        subtotal: 48.0,
      },
    ],
    total: 168.0,
    status: "entregue",
    payment_method: "cartao_credito",
    created_at: "2026-04-28",
  },
  {
    id: "5",
    client_id: "4",
    client_name: "Fernanda Costa",
    items: [
      {
        product_id: "8",
        product_name: "Shampoo Cachos Definidos",
        quantity: 2,
        unit_price: 42.0,
        subtotal: 84.0,
      },
    ],
    total: 84.0,
    status: "pendente",
    payment_method: "fiado",
    created_at: "2026-05-15",
  },
];

export const mockSchedule: ScheduleEvent[] = [
  {
    id: "1",
    client_id: "3",
    client_name: "Juliana Mendes",
    type: "follow_up",
    title: "Follow-up prospect Juliana",
    description: "Ligar para apresentar o catálogo de maio",
    date: "2026-05-17",
    completed: false,
  },
  {
    id: "2",
    client_id: "5",
    client_name: "Beatriz Lima",
    type: "follow_up",
    title: "Reativar cliente Beatriz",
    description: "Verificar interesse em novos produtos",
    date: "2026-05-18",
    completed: false,
  },
  {
    id: "3",
    client_id: "2",
    client_name: "Camila Rodrigues",
    type: "entrega",
    title: "Entrega pedido #2",
    description: "Hidratante + Creme anti-idade",
    date: "2026-05-16",
    completed: false,
  },
  {
    id: "4",
    client_id: "6",
    client_name: "Mariana Souza",
    type: "entrega",
    title: "Entrega pedido #3",
    description: "Perfume Floral",
    date: "2026-05-19",
    completed: false,
  },
  {
    id: "5",
    client_id: "1",
    client_name: "Ana Paula Ferreira",
    type: "aniversario",
    title: "Aniversário Ana Paula",
    description: "Enviar mensagem e oferecer desconto especial",
    date: "2026-05-20",
    completed: false,
  },
];

export const mockDashboardStats: DashboardStats = {
  total_clients: 6,
  active_clients: 4,
  total_orders: 5,
  revenue_month: 638.0,
  revenue_prev_month: 520.0,
  pending_orders: 2,
  top_products: [
    { name: "Base Líquida", quantity: 8, revenue: 680.0 },
    { name: "Hidratante FPS 30", quantity: 6, revenue: 330.0 },
    { name: "Batom Matte", quantity: 11, revenue: 418.0 },
    { name: "Paleta Sombras", quantity: 4, revenue: 480.0 },
    { name: "Perfume Floral", quantity: 3, revenue: 216.0 },
  ],
  monthly_revenue: [
    { month: "Dez", revenue: 380 },
    { month: "Jan", revenue: 520 },
    { month: "Fev", revenue: 410 },
    { month: "Mar", revenue: 680 },
    { month: "Abr", revenue: 520 },
    { month: "Mai", revenue: 638 },
  ],
};
